language: python

python:
  - "3.8"

install:
  - pip install black flake8 flake8-bugbear flake8-builtins flake8-comprehensions flake8-docstrings flake8-rst-docstrings mypy

script:
  - black -q --diff --check .
  - flake8 .
  - mypy --config-file .mypy.ini .
